version: "2.4"
services:
  rails:
    build:
      context: .
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    command: /bin/sh -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000

volumes:
  bundle:
