version: "2.4"
services:
  rails: &base
    build:
      context: .
    environment:
      SCOUT_NAME: With Controller
    volumes:
      - .:/myapp
      - /tmp/scout/rails/tmp:/myapp/tmp
      - /tmp/scout/rails/log:/myapp/log
      - bundle-rails:/usr/local/bundle
    command: /bin/sh -c "rm -f /tmp/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -P /tmp/server.pid"
    ports:
      - 3000:3000

  rails-gql-scout:
    <<: *base
    environment:
      ENABLE_GRAPHQL_SCOUT: y
      SCOUT_NAME: With GraphQL Tracing
    volumes:
      - .:/myapp
      - /tmp/scout/gql/tmp:/myapp/tmp
      - /tmp/scout/gql/log:/myapp/log
      - bundle-rails-gql-scout:/usr/local/bundle
    ports:
      - 3001:3000

  rails-gql-scout-rename:
    <<: *base
    environment:
      ENABLE_GRAPHQL_SCOUT: y
      ENABLE_GRAPHQL_RENAME: y
      SCOUT_NAME: With GraphQL Tracing Rename
    volumes:
      - .:/myapp
      - /tmp/scout/gql-rename/tmp:/myapp/tmp
      - /tmp/scout/gql-rename/log:/myapp/log
      - bundle-rails-gql-scout-rename:/usr/local/bundle
    ports:
      - 3002:3000
volumes:
  bundle-rails:
  bundle-rails-gql-scout:
  bundle-rails-gql-scout-rename:
